version: '3.5'

services:
  mongodb:
    image: mongo:4.2.3
    container_name: "mongodb"
    environment:
      - MONGO_USER=mongodb
      #- MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=vivid-streets
    volumes:
      - ./mongo-seed/init.js:/docker-entrypoint-initdb.d/init.js
    #  - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --quiet
    
  flask-api:
    container_name: app-app
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/usr/src/app"
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/vivid-streets
    env_file:
      - backend-secret.env
    depends_on:
      - mongodb

  client:
    container_name: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'
    tty: true
    depends_on:
      - flask-api
    environment:
      - PORT=80
      - NODE_ENV=development
      - NODE_PATH=/usr/src/app/node_modules
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - react-secret.env

